"""Bake the all-England corpus + reference data into site/data.json.

v6 (topic momentum + document search): adds monthly topic share time-series
and trend direction per council (momentum), and per-council search indexes
(generated by build_search.py with 500 recent classified docs each).

v5 (all-England): the site now covers every English council in the Council Gateway
(282 = 267 harvested into data_england/c<id>/ + the original 15 in data_fy1..7/).
The universal join key is the ONS LAD code. data_england/scorecard_imd.csv is the
master registry (one row per council per IMD domain; distinct ons_code = the 282).

Sources, all joined on ons_code unless noted:
  - discussion corpus : data_fy1..7/doc_topics.csv + data_england/c*/doc_topics.csv
                        (joined council_id -> ons_code; duplicate gateway ids for
                        the same ons_code are summed)
  - finance (£/res)   : data_england/finance_all.csv  + population_all.csv  (all 282)
  - deprivation       : data_england/scorecard_imd.csv (IoD2025, 8 domains)
  - control / party   : data_england/control_all.csv   (Open Council Data UK, 2026)
  - ethnicity/age%    : data_england/ethnicity_all.csv (282 + England, APS or Census)
  - age pyramid       : data/age_bands.csv        (original 15 + England only)
  - reading links     : data/reading_links.csv    (original 15 only)
  - election banner    : data/elections.csv        (original 15 only)
  - momentum           : computed from discussion corpus monthly breakdown (218+ councils)

Every panel degrades: a council with no input for a panel is simply omitted from it.
Reads only; writes only site/data.json. Idempotent. Run: python site/build.py
"""
import json
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
ENG_DIR = ROOT / "data_england"
SITE_DIR = Path(__file__).parent

sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).parent))
from taxonomy import TOPICS as TOPIC_KEYWORDS  # noqa: E402
from common import load_registry  # noqa: E402

NOTICE_PATTERN = r"(?i)\border\b|notice|traffic|speed limit|parking|prohibition|public path"

TOPICS = list(TOPIC_KEYWORDS.keys())
_SAFE = px.colors.qualitative.Safe
TOPIC_COLORS = {t: _SAFE[i] for i, t in enumerate(TOPICS)}
NEUTRAL_GREY = _SAFE[10]
TAXONOMY_EXAMPLES = {t: ", ".join(kws[:5]) for t, kws in TOPIC_KEYWORDS.items()}

# service -> topic mapping used to restrict talk-vs-spend to topics with a budget line.
SERVICE_TO_TOPIC = {
    "Education services": "Children & Education",
    "Highways and transport services": "Transport & Highways",
    "Children Social Care": "Children & Education",
    "Adult Social Care": "Social Care",
    "Public Health": "Health",
    "Housing services (GFRA only)": "Housing & Planning",
    "Cultural and related services": "Local Economy",
    "Environmental and regulatory services": "Climate & Environment",
    "Planning and development services": "Housing & Planning",
}
MATCHED_SPEND_TOPICS = sorted(set(SERVICE_TO_TOPIC.values()))

# IoD2025 deprivation domains (scorecard_imd.csv) and their reader-facing labels.
DOMAINS = ["IMD", "Income", "Employment", "Education", "Health", "Crime", "Barriers", "Living"]
DOMAIN_LABELS = {
    "IMD": "Overall deprivation",
    "Income": "Income",
    "Employment": "Employment",
    "Education": "Education & skills",
    "Health": "Health & disability",
    "Crime": "Crime",
    "Barriers": "Barriers to housing & services",
    "Living": "Living environment",
}
# fixed National-view bucket order (matches control_all.py buckets, excludes Independent/Other)
BUCKET_ORDER = ["Labour", "Conservative", "Liberal Democrat", "Reform UK", "Green"]

AGE_BAND_ORDER = ["0-15", "16-29", "30-44", "45-64", "65+"]


def read_csv_optional(path, **kwargs):
    try:
        return pd.read_csv(path, **kwargs)
    except FileNotFoundError:
        return None


def read_shard_csv(path):
    if not path.exists():
        return None
    try:
        df = pd.read_csv(path)
    except (pd.errors.EmptyDataError, pd.errors.ParserError, OSError, ValueError) as e:
        print(f"  skipping incomplete shard {path}: {e}")
        return None
    return None if df.empty else df


# ------------------------------------------------------------------ registry ---
# load_registry() lives in site/common.py so build.py and build_search.py share it.


# -------------------------------------------------------------------- corpus ---
def _load_raw_corpus(id2ons):
    """Load and filter the full corpus once. Returns DataFrame."""
    frames = []
    for i in range(1, 8):
        df = read_shard_csv(ROOT / f"data_fy{i}" / "doc_topics.csv")
        if df is not None:
            frames.append(df)
    for d in sorted(ENG_DIR.glob("c*/doc_topics.csv")):
        df = read_shard_csv(d)
        if df is not None:
            frames.append(df)
    if not frames:
        return None
    corpus = pd.concat(frames, ignore_index=True)
    if "committee" in corpus.columns:
        corpus = corpus[~corpus["committee"].str.contains(NOTICE_PATTERN, na=False)]
    for t in TOPICS:
        if t not in corpus.columns:
            corpus[t] = 0
    corpus["ons_code"] = corpus["council_id"].map(id2ons)
    corpus = corpus[corpus["ons_code"].notna()]
    return corpus


def load_corpus_by_ons(id2ons):
    """{ons_code: {topic: pct}} — aggregate topic shares per council."""
    corpus = _load_raw_corpus(id2ons)
    if corpus is None:
        return {}
    sums = corpus.groupby("ons_code")[TOPICS].sum()
    shares = {}
    for code, row in sums.iterrows():
        total = row.sum()
        if total > 0:
            shares[code] = (row / total * 100).round(1).to_dict()
    return shares


def corpus_window(id2ons):
    """Human-readable date span + document count of the loaded discussion corpus."""
    corpus = _load_raw_corpus(id2ons)
    if corpus is None or corpus.empty:
        return None
    d = pd.to_datetime(corpus["date"], errors="coerce").dropna()
    if d.empty:
        return None
    lo, hi = d.min(), d.max()
    return {
        "from": lo.date().isoformat(),
        "to": hi.date().isoformat(),
        "label": f"{lo.strftime('%b %Y')} – {hi.strftime('%b %Y')}",
        "docs": int(len(corpus)),
    }


def load_corpus_momentum(id2ons):
    """Monthly topic shares per council for momentum tracking.
    Returns {ons_code: {months: [str], series: {topic: [pct]}, changes: [...]}}.
    Each council also gets min_doc_count for the frontend to assess reliability."""
    corpus = _load_raw_corpus(id2ons)
    if corpus is None or corpus.empty:
        return {}

    # Extract month from ISO date string (first 7 chars: YYYY-MM)
    corpus["month"] = corpus["date"].str[:7]
    # Drop rows with unparseable dates
    corpus = corpus[corpus["month"].notna() & (corpus["month"].str.match(r"\d{4}-\d{2}"))]

    # Aggregate topic hits per (ons_code, month)
    agg_dict = {"doc_id": "count"}
    for t in TOPICS:
        agg_dict[t] = "sum"
    monthly = corpus.groupby(["ons_code", "month"]).agg(agg_dict).rename(columns={"doc_id": "doc_count"})
    monthly = monthly.reset_index()

    # Build per-council structures
    momentum = {}
    for (code, month), row in monthly.groupby(["ons_code", "month"], sort=False).first().iterrows():
        # Prefer the iterrows() output since reset_index may not work cleanly with groupby
        pass

    # Simpler: iterate reset_index rows
    by_code = {}
    for _, row in monthly.iterrows():
        code = row["ons_code"]
        month = row["month"]
        mth_data = {"doc_count": int(row["doc_count"])}
        total = sum(row[t] for t in TOPICS)
        if total > 0:
            mth_data["shares"] = {t: round(row[t] / total * 100, 1) for t in TOPICS if row[t] > 0}
        else:
            mth_data["shares"] = {}
        by_code.setdefault(code, {})[month] = mth_data

    # Compute momentum trends for each council
    MIN_DOCS_PER_WINDOW = 5
    for code, trends in by_code.items():
        months = sorted(trends.keys())
        if len(months) < 4:
            continue

        # Recent = last 2 months, Prior = 2 before that
        recent_months = months[-2:]
        prior_months = months[-4:-2]

        # Aggregate topic hits across each window
        recent_agg = {}
        recent_docs = 0
        for m in recent_months:
            for t, v in trends[m]["shares"].items():
                recent_agg[t] = recent_agg.get(t, 0) + v
            recent_docs += trends[m]["doc_count"]

        prior_agg = {}
        prior_docs = 0
        for m in prior_months:
            for t, v in trends[m]["shares"].items():
                prior_agg[t] = prior_agg.get(t, 0) + v
            prior_docs += trends[m]["doc_count"]

        if recent_docs < MIN_DOCS_PER_WINDOW or prior_docs < MIN_DOCS_PER_WINDOW:
            continue

        n_recent = len(recent_months)
        n_prior = len(prior_months)
        recent_avg = {t: v / n_recent for t, v in recent_agg.items()}
        prior_avg = {t: v / n_prior for t, v in prior_agg.items()}

        changes = []
        for topic in TOPICS:
            r = recent_avg.get(topic, 0.0)
            p = prior_avg.get(topic, 0.0)
            change = round(r - p, 1)
            direction = "rising" if change > 1.0 else ("declining" if change < -1.0 else "stable")
            changes.append({
                "topic": topic,
                "change_pp": change,
                "recent_avg": round(r, 1),
                "prior_avg": round(p, 1),
                "direction": direction,
            })
        changes.sort(key=lambda x: -abs(x["change_pp"]))

        # Series data for the line chart: one array per topic across months
        series = {}
        for topic in TOPICS:
            vals = [trends[m]["shares"].get(topic, 0.0) for m in months]
            series[topic] = vals

        momentum[code] = {
            "months": months,
            "series": series,
            "changes": changes,
            "min_doc_count": min(trends[m]["doc_count"] for m in months),
        }

    return momentum


# ------------------------------------------------------------------- finance ---
def load_finance_by_ons():
    """{ons_code: {service: spend_gbp_thousands}} from finance_all.csv (all 282)."""
    fa = pd.read_csv(ENG_DIR / "finance_all.csv")
    # suppressed values ('[x]') and any non-numeric -> dropped (drop-don't-fake)
    fa["spend_gbp_thousands"] = pd.to_numeric(fa["spend_gbp_thousands"], errors="coerce")
    fa = fa[fa["spend_gbp_thousands"].notna()]
    out = {}
    for code, grp in fa.groupby("ons_code"):
        out[code] = dict(zip(grp["service"], grp["spend_gbp_thousands"]))
    return out


def money_per_resident(services, pop):
    if not services or not pop:
        return None
    rows = [{"service": s, "gbp_per_resident": round(v * 1000 / pop, 1)} for s, v in services.items()]
    rows.sort(key=lambda r: -r["gbp_per_resident"])
    return rows


def finance_topic_shares(services):
    """Council's spend share across the 7 matched topics, from its service spend."""
    if not services:
        return None
    by_topic = {}
    for svc, spend in services.items():
        topic = SERVICE_TO_TOPIC.get(svc)
        if topic:
            by_topic[topic] = by_topic.get(topic, 0) + spend
    total = sum(by_topic.values())
    if total <= 0:
        return None
    return {t: round(by_topic[t] / total * 100, 1) for t in by_topic}


# ---------------------------------------------------------------- deprivation ---
def load_scorecard(reg):
    """{ons_code: [8 domain dicts]} from scorecard_imd.csv, in DOMAIN order."""
    imd = pd.read_csv(ENG_DIR / "scorecard_imd.csv")
    out = {}
    for code, grp in imd.groupby("ons_code"):
        g = grp.set_index("domain")
        row = []
        for dom in DOMAINS:
            if dom not in g.index:
                continue
            d = g.loc[dom]
            row.append({
                "domain": dom, "label": DOMAIN_LABELS[dom],
                "rank": int(d["rank"]), "pool_n": int(d["pool_n"]), "tier": d["tier"],
                "decile": int(d["decile"]), "score": float(d["score"]), "prop10": float(d["prop10"]),
            })
        out[code] = row
    return out


# -------------------------------------------------------------------- control ---
def load_control():
    """{ons_code: {current, since, since_year, previous, changed, bucket}}."""
    df = read_csv_optional(ENG_DIR / "control_all.csv")
    if df is None:
        return {}
    out = {}
    for _, r in df.iterrows():
        yr = int(r["since_year"])
        since = "2016 or earlier" if yr <= 2016 else str(yr)
        changed = bool(r["changed"])
        out[r["ons_code"]] = {
            "current": r["control_label"], "since": since, "since_year": yr,
            "previous": r["previous_label"] if changed and r["previous_label"] else None,
            "changed": changed, "bucket": r["bucket"],
        }
    return out


# ----------------------------------------------------------------- aggregates ---
def party_groups(share_lookup, bucket_of, label_key):
    """Equal-weighted mean share per control bucket over members present in share_lookup."""
    groups = []
    for bucket in BUCKET_ORDER:
        members = [n for n in share_lookup if bucket_of.get(n) == bucket]
        if not members:
            continue
        series = [pd.Series(share_lookup[n]) for n in members]
        mean_share = pd.concat(series, axis=1).mean(axis=1).round(1).to_dict()
        groups.append({"party": bucket, "n": len(members), "councils": sorted(members), label_key: mean_share})
    return groups


# ------------------------------------------------------- watchdog / finance ---
def _f(v):
    try:
        if pd.isna(v):
            return None
        return float(v)
    except (TypeError, ValueError):
        return None


def load_ombudsman():
    """{ons_code: {upheld, uphold_rate, uphold_rate_peer, per_100k, compliance_rate}}."""
    df = read_csv_optional(ENG_DIR / "ombudsman.csv")
    if df is None:
        return {}
    out = {}
    for _, r in df.iterrows():
        out[r["ons_code"]] = {
            "complaints_total": _f(r.get("complaints_total")),
            "upheld": _f(r.get("upheld")),
            "uphold_rate": _f(r.get("uphold_rate")),
            "uphold_rate_peer": _f(r.get("uphold_rate_peer")),
            "per_100k": _f(r.get("per_100k")),
            "per_100k_peer": _f(r.get("per_100k_peer")),
            "compliance_rate": _f(r.get("compliance_rate")),
        }
    return out


def load_borrowing():
    """{ons_code: {total_gbp_m}}."""
    df = read_csv_optional(ENG_DIR / "borrowing.csv")
    if df is None:
        return {}
    return {r["ons_code"]: {"total_gbp_m": _f(r.get("total_borrowing_gbp_m"))}
            for _, r in df.iterrows()}


def load_contracts():
    """{ons_code: [ {supplier, value_gbp, n, latest}, ... ]} sorted by value desc."""
    df = read_csv_optional(ENG_DIR / "contracts.csv")
    if df is None:
        return {}
    out = {}
    for code, grp in df.groupby("ons_code"):
        recs = []
        for _, r in grp.sort_values("total_value_gbp", ascending=False).iterrows():
            recs.append({
                "supplier": r["supplier"],
                "value_gbp": _f(r["total_value_gbp"]),
                "n": int(r["n_contracts"]),
                "latest": str(r["latest_award"]) if pd.notna(r["latest_award"]) else None,
            })
        out[code] = recs
    return out


def load_portals():
    """{ons_code: {portal_url, official_name}} from data_england/council_portals.csv."""
    df = read_csv_optional(ENG_DIR / "council_portals.csv")
    if df is None:
        return {}
    out = {}
    for _, r in df.iterrows():
        out[r["ons_code"]] = {
            "portal_url": r.get("portal_url") if isinstance(r.get("portal_url"), str) else None,
            "official_name": r.get("official_name") if isinstance(r.get("official_name"), str) else None,
        }
    return out


def _ratio(price, weekly_pay):
    try:
        price = float(price)
        pay = float(weekly_pay) * 52.0
    except (TypeError, ValueError):
        return None
    if pay <= 0 or price <= 0:
        return None
    return round(price / pay, 1)


def load_house_earnings(reg):
    """{ons_code: house-price-to-earnings ratio} plus the England ratio.
    Ratio = HM Land Registry average house price / (ASHE median full-time weekly pay x 52).
    Primary source data_england/profile_all.csv; legacy data/profile.csv (by name) fills gaps."""
    out, eng = {}, None
    pa = read_csv_optional(ENG_DIR / "profile_all.csv")
    if pa is not None:
        for _, r in pa.iterrows():
            v = _ratio(r.get("median_house_price"), r.get("median_ft_pay"))
            if v is not None:
                out[r["ons_code"]] = v
    po = read_csv_optional(DATA_DIR / "profile.csv")
    if po is not None:
        name2code = {r["name"]: code for code, r in reg.items()}
        for _, r in po.iterrows():
            v = _ratio(r.get("median_house_price"), r.get("median_ft_pay"))
            if v is None:
                continue
            if r["council"] == "England":
                eng = v
            else:
                code = name2code.get(r["council"])
                if code and code not in out:
                    out[code] = v
    return out, eng


def borrowing_england(borrowing, population):
    """England borrowing benchmarks + per-council rank (1 = most indebted)."""
    per = {}
    for code, b in borrowing.items():
        pop = population.get(code)
        if b.get("total_gbp_m") is not None and pop:
            per[code] = b["total_gbp_m"] * 1_000_000 / pop
    if not per:
        return {}, {}
    total_gbp = sum(borrowing[c]["total_gbp_m"] for c in per) * 1_000_000
    total_pop = sum(population[c] for c in per)
    vals = sorted(per.values())
    n = len(vals)
    median = vals[n // 2] if n % 2 else (vals[n // 2 - 1] + vals[n // 2]) / 2
    agg = {
        "mean_per_resident": round(total_gbp / total_pop),
        "median_per_resident": round(median),
        "total_gbp_bn": round(total_gbp / 1_000_000_000, 1),
        "n": n,
    }
    # rank 1 = highest debt per resident
    ranked = sorted(per.items(), key=lambda kv: -kv[1])
    ranks = {code: i for i, (code, _) in enumerate(ranked, 1)}
    return agg, ranks


def tier_bucket(la_class):
    """Map an RSX class to a comparison tier for party aggregates."""
    if la_class in ("UA", "MD", "LB"):
        return "single"
    if la_class == "SD":
        return "district"
    if la_class == "SC":
        return "county"
    return "other"


def main():
    reg = load_registry()
    id2ons = {r["council_id"]: code for code, r in reg.items() if r["council_id"] is not None}

    corpus_shares = load_corpus_by_ons(id2ons)                 # ons -> {topic: pct}
    window = corpus_window(id2ons)                             # {from,to,label,docs}
    finance_by_ons = load_finance_by_ons()                     # ons -> {service: spend_k}
    scorecard = load_scorecard(reg)                            # ons -> [8 domains]
    control = load_control()                                   # ons -> {...}
    borrowing = load_borrowing()                               # ons -> {total_gbp_m}
    contracts = load_contracts()                               # ons -> [suppliers]
    portal_by_ons = load_portals()                             # ons -> official committee portal

    pop_df = read_csv_optional(ENG_DIR / "population_all.csv")
    population = dict(zip(pop_df["ons_code"], pop_df["population"])) if pop_df is not None else {}

    borrow_eng, borrow_rank = borrowing_england(borrowing, population)

    # Shire District -> Parent County & Authority Class lookup
    lad2cty_df = read_csv_optional(ENG_DIR / "lad_to_county_2023.csv")
    parent_county_map = dict(zip(lad2cty_df["LAD23CD"], lad2cty_df["CTY23NM"])) if lad2cty_df is not None else {}
    parent_county_code_map = dict(zip(lad2cty_df["LAD23CD"], lad2cty_df["CTY23CD"])) if lad2cty_df is not None else {}
    
    fin_df = read_csv_optional(ENG_DIR / "finance_all.csv")
    la_class_raw = dict(zip(fin_df["ons_code"], fin_df["class"])) if fin_df is not None else {}
    CLASS_LABELS = {
        "SD": "Shire District (Lower Tier)",
        "SC": "County Council (Upper Tier)",
        "UA": "Unitary Authority (Single Tier)",
        "MD": "Metropolitan Borough (Single Tier)",
        "LB": "London Borough (Single Tier)",
    }

    # ethnicity/age%: ethnicity_all.csv (282 + England, by ons_code, with source tag)
    eth_all = read_csv_optional(ENG_DIR / "ethnicity_all.csv")
    eth_by_ons = {}
    ethnicity_england = None
    if eth_all is not None:
        for _, p in eth_all.iterrows():
            if pd.notna(p.get("white_pct")):
                e = {"White": p["white_pct"], "Asian": p["asian_pct"],
                     "Black": p["black_pct"], "Mixed": p["mixed_pct"], "Other": p["other_pct"],
                     "source": p["source"]}
                if p["ons_code"] == "E92000001":
                    ethnicity_england = {k: v for k, v in e.items() if k != "source"}
                else:
                    eth_by_ons[p["ons_code"]] = e
    # source lookup: ons_code -> source tag
    eth_source_by_ons = {}
    for code, e in eth_by_ons.items():
        src = e.pop("source", None)
        if src:
            eth_source_by_ons[code] = src

    # legacy fallback (Census 2021 for original 15 if new file absent)
    if not eth_by_ons:
        profile_all = read_csv_optional(ENG_DIR / "profile_all.csv")
        profile_old = read_csv_optional(DATA_DIR / "profile.csv")
        if profile_all is not None:
            for _, p in profile_all.iterrows():
                if pd.notna(p.get("white_pct")):
                    eth_by_ons[p["ons_code"]] = {"White": p["white_pct"], "Asian": p["asian_pct"],
                                                 "Black": p["black_pct"], "Mixed": p["mixed_pct"], "Other": p["other_pct"]}
        if profile_old is not None:
            for _, p in profile_old.iterrows():
                if pd.notna(p.get("white_pct")):
                    e = {"White": p["white_pct"], "Asian": p["asian_pct"], "Black": p["black_pct"],
                         "Mixed": p["mixed_pct"], "Other": p["other_pct"]}
                    if p["council"] == "England":
                        ethnicity_england = e
                    else:
                        name = p["council"]
                        code = next((c for c, r in reg.items() if r["name"] == name), None)
                        if code:
                            eth_by_ons.setdefault(code, e)

    elections = read_csv_optional(DATA_DIR / "elections.csv")
    reading_links = read_csv_optional(DATA_DIR / "reading_links.csv")
    age_bands = read_csv_optional(ENG_DIR / "age_bands_all.csv")
    if age_bands is None:
        age_bands = read_csv_optional(DATA_DIR / "age_bands.csv")

    # ---- Quality of Life (QoL) & Financial Distress datasets ----------------
    qol_df = read_csv_optional(ENG_DIR / "qol_all.csv")
    qol_by_code = {}
    qol_england = {}
    if qol_df is not None:
        eng_row = qol_df[qol_df["ons_code"] == "E92000001"]
        if not eng_row.empty:
            er = eng_row.iloc[0]
            qol_england = {
                "life_expectancy": er["life_expectancy"],
                "rent_affordability": er["rent_affordability"],
                "attainment8": er["attainment8"],
                "air_quality_pm25_pct": er["air_quality_pm25_pct"],
                "child_poverty_pct": er["child_poverty_pct"],
                "claimant_rate_pct": er["claimant_rate_pct"],
                "crime_per_1000": er["crime_per_1000"],
            }
        for _, qr in qol_df.iterrows():
            code = qr["ons_code"]
            if code == "E92000001":
                continue
            qol_by_code[code] = {
                "life_expectancy": qr["life_expectancy"],
                "life_expectancy_rank": int(qr["life_expectancy_rank"]) if pd.notna(qr["life_expectancy_rank"]) else None,
                "attainment8": qr["attainment8"],
                "attainment8_rank": int(qr["attainment8_rank"]) if pd.notna(qr["attainment8_rank"]) else None,
                "rent_affordability": qr["rent_affordability"],
                "rent_affordability_rank": int(qr["rent_affordability_rank"]) if pd.notna(qr["rent_affordability_rank"]) else None,
                "air_quality_pm25_pct": qr["air_quality_pm25_pct"],
                "air_quality_rank": int(qr["air_quality_rank"]) if pd.notna(qr["air_quality_rank"]) else None,
                "child_poverty_pct": qr["child_poverty_pct"],
                "child_poverty_rank": int(qr["child_poverty_rank"]) if pd.notna(qr["child_poverty_rank"]) else None,
                "claimant_rate_pct": qr["claimant_rate_pct"],
                "claimant_rate_rank": int(qr["claimant_rate_rank"]) if pd.notna(qr["claimant_rate_rank"]) else None,
                "crime_per_1000": qr["crime_per_1000"],
                "crime_rank": int(qr["crime_rank"]) if pd.notna(qr["crime_rank"]) else None,
            }

    # house-price-to-earnings ratio (HPI average price / ASHE annual full-time pay)
    house_earn, house_earn_eng = load_house_earnings(reg)
    for code in qol_by_code:
        qol_by_code[code]["house_earnings"] = house_earn.get(code)
    if qol_england:
        qol_england["house_earnings"] = house_earn_eng

    distress_df = read_csv_optional(ENG_DIR / "financial_distress.csv")
    distress_by_code = {}
    distress_watchlist = []
    if distress_df is not None:
        for _, dr in distress_df.iterrows():
            code = dr["ons_code"]
            d_rec = {
                "is_s114": bool(dr["is_s114"]),
                "s114_year": int(dr["s114_year"]) if pd.notna(dr["s114_year"]) else None,
                "s114_details": dr["s114_details"] if pd.notna(dr["s114_details"]) else "",
                "is_efs": bool(dr["is_efs"]),
                "efs_amount_gbp_m": float(dr["efs_amount_gbp_m"]) if pd.notna(dr["efs_amount_gbp_m"]) else None,
                "efs_details": dr["efs_details"] if pd.notna(dr["efs_details"]) else "",
                "is_audit_delayed": bool(dr["is_audit_delayed"]),
                "distress_status": dr["distress_status"],
                "severity": int(dr["severity"]),
            }
            distress_by_code[code] = d_rec
            if d_rec["severity"] > 0:
                distress_watchlist.append({
                    "council": dr["council"],
                    "ons_code": code,
                    "status": dr["distress_status"],
                    "severity": d_rec["severity"],
                    "efs_m": d_rec["efs_amount_gbp_m"],
                    "s114_year": d_rec["s114_year"],
                })
        distress_watchlist.sort(key=lambda x: -x["severity"])

    # ---- per-council derived: money, money_share, talk_vs_spend, topic_share ----
    council_names = sorted(r["name"] for r in reg.values())
    name2ons = {r["name"]: code for code, r in reg.items()}

    topic_share = {code: corpus_shares.get(code) for code in reg}
    money = {}
    ft_shares = {}   # name -> {topic: pct}
    for code, r in reg.items():
        money[code] = money_per_resident(finance_by_ons.get(code), population.get(code))
        fts = finance_topic_shares(finance_by_ons.get(code))
        if fts:
            ft_shares[r["name"]] = fts

    # ---- Population-weighted spend benchmarks across England -----------------
    all_spend_by_service = {}
    total_pop_for_finance = 0
    for code, services in finance_by_ons.items():
        pop = population.get(code)
        if pop and services:
            total_pop_for_finance += pop
            for s, val in services.items():
                all_spend_by_service[s] = all_spend_by_service.get(s, 0) + val

    if total_pop_for_finance > 0:
        money_weighted_avg = {
            s: round(spend_k * 1000 / total_pop_for_finance, 1)
            for s, spend_k in all_spend_by_service.items()
        }
        # Population-weighted topic spend share
        topic_spend_england = {}
        for svc, spend_k in all_spend_by_service.items():
            top = SERVICE_TO_TOPIC.get(svc)
            if top:
                topic_spend_england[top] = topic_spend_england.get(top, 0) + spend_k

        tot_top_spend = sum(topic_spend_england.values())
        ft_england = {t: round(amt / tot_top_spend * 100, 1) for t, amt in topic_spend_england.items()} if tot_top_spend > 0 else {}
    else:
        money_weighted_avg = {}
        ft_england = {}

    corpus_avg = (pd.concat([pd.Series(corpus_shares[c]) for c in corpus_shares], axis=1).mean(axis=1).round(1).to_dict()
                  if corpus_shares else {})

    # ---- age bands (original 15 + England only) --------------------------------
    age_mode = age_pyramid_england = age_bands_england = None
    age_by_name = {}
    if age_bands is not None and "sex" in age_bands.columns:
        age_mode = "pyramid"
        for cname in council_names + ["England"]:
            a = age_bands[age_bands["council"] == cname]
            if a.empty:
                continue
            pyr = {}
            for band in AGE_BAND_ORDER:
                b = a[a["band"] == band]
                if not b.empty:
                    pyr[band] = {"male": b.loc[b["sex"] == "male", "pct"].sum(),
                                 "female": b.loc[b["sex"] == "female", "pct"].sum()}
            if pyr:
                if cname == "England":
                    age_pyramid_england = pyr
                else:
                    age_by_name[cname] = pyr
    elif age_bands is not None:
        age_mode = "paired"
        eng = age_bands[age_bands["council"] == "England"]
        if not eng.empty:
            age_bands_england = eng.set_index("band")["pct"].to_dict()
        for cname in council_names:
            a = age_bands[age_bands["council"] == cname]
            if not a.empty:
                age_by_name[cname] = a.set_index("band")["pct"].to_dict()

    # ---- party buckets (over control) -----------------------------------------
    bucket_of = {r["name"]: control.get(code, {}).get("bucket") for code, r in reg.items()}
    disc_share_by_name = {r["name"]: corpus_shares[code] for code, r in reg.items() if code in corpus_shares}
    party_groups_spend = party_groups(ft_shares, bucket_of, "spend_share")
    party_groups_discussion = party_groups(disc_share_by_name, bucket_of, "discussion_share")

    # tier-aware party aggregates: same views restricted to a comparable tier so
    # single-tier unitaries aren't averaged with two-tier districts (Simpson's paradox)
    class_of = {r["name"]: la_class_raw.get(code) for code, r in reg.items()}
    tier_of = {n: tier_bucket(c) for n, c in class_of.items()}
    TIER_KEYS = ["single", "district", "county"]
    party_by_tier = {}
    for tk in TIER_KEYS:
        spend_sub = {n: v for n, v in ft_shares.items() if tier_of.get(n) == tk}
        disc_sub = {n: v for n, v in disc_share_by_name.items() if tier_of.get(n) == tk}
        party_by_tier[tk] = {
            "spend": party_groups(spend_sub, bucket_of, "spend_share"),
            "discussion": party_groups(disc_sub, bucket_of, "discussion_share"),
            "n_councils": sum(1 for n in bucket_of if tier_of.get(n) == tk),
        }

    # ---- league table (all councils, QoL indicators) -------------------------
    QOL_INDICATORS = [
        {"id": "life_expectancy", "label": "Life Expectancy", "unit": " yrs", "lower_better": False},
        {"id": "attainment8", "label": "GCSE Attainment", "unit": " pts", "lower_better": False},
        {"id": "rent_affordability", "label": "Rent Affordability", "unit": "%", "lower_better": True},
        {"id": "child_poverty_pct", "label": "Child Poverty", "unit": "%", "lower_better": True},
        {"id": "claimant_rate_pct", "label": "Claimant Rate", "unit": "%", "lower_better": True},
        {"id": "air_quality_pm25_pct", "label": "Air Quality (PM2.5)", "unit": "%", "lower_better": True},
        {"id": "crime_per_1000", "label": "Crime / 1k", "unit": "", "lower_better": True},
        {"id": "house_earnings", "label": "House / Earnings", "unit": "×", "lower_better": True},
    ]

    league_rows = []
    for code, r in reg.items():
        ctrl = control.get(code, {})
        q = qol_by_code.get(code, {})
        
        row = {
            "council": r["name"],
            "ons_code": code,
            "tier": r["tier"],
            "control": ctrl.get("current"),
            "bucket": ctrl.get("bucket"),
            "life_expectancy": q.get("life_expectancy"),
            "attainment8": q.get("attainment8"),
            "rent_affordability": q.get("rent_affordability"),
            "child_poverty_pct": q.get("child_poverty_pct"),
            "claimant_rate_pct": q.get("claimant_rate_pct"),
            "air_quality_pm25_pct": q.get("air_quality_pm25_pct"),
            "crime_per_1000": q.get("crime_per_1000"),
            "house_earnings": q.get("house_earnings"),
        }
        league_rows.append(row)
    league_table = {"indicators": QOL_INDICATORS, "rows": league_rows}

    # ---- assemble councils ----------------------------------------------------
    out_councils = {}
    for code, r in reg.items():
        cname = r["name"]
        ctrl = control.get(code)

        elec = None
        if elections is not None:
            e = elections[elections["council"] == cname].sort_values("poll_date")
            if not e.empty:
                elec = {"title": e.iloc[0]["title"], "poll_date": e.iloc[0]["poll_date"]}

        ethnicity = eth_by_ons.get(code)

        m_share = None
        if cname in ft_shares:
            rows = sorted(ft_shares[cname].items(), key=lambda kv: -kv[1])
            m_share = [{"topic": t, "council_pct": p, "england_pct": round(ft_england.get(t, 0.0), 1)} for t, p in rows]

        tvs = None
        if code in corpus_shares and cname in ft_shares:
            matched = [t for t in MATCHED_SPEND_TOPICS if t in ft_shares[cname]]
            disc_matched = {t: corpus_shares[code].get(t, 0.0) for t in matched}
            tot = sum(disc_matched.values())
            if tot > 0 and matched:
                disc_pct = {t: round(disc_matched[t] / tot * 100, 1) for t in matched}
                note = "spend committed under the previous administration" if (ctrl and ctrl["changed"]) else None
                tvs = {"topics": [{"topic": t, "discussion_pct": disc_pct[t], "spend_pct": ft_shares[cname][t]} for t in matched],
                       "note": note}

        links = []
        if reading_links is not None:
            rl = reading_links[reading_links["council"] == cname].head(3)
            links = rl[["title", "url", "source"]].to_dict("records")

        # Official records: direct links to the council's own democratic portal and
        # national statutory bodies. Replaces the old generic Google/BBC searches.
        meta = portal_by_ons.get(code) or {}
        off_name = meta.get("official_name") or f"{cname} Council"
        official_links = []
        if meta.get("portal_url"):
            official_links.append({
                "title": f"{cname} committee meetings, agendas & minutes (official)",
                "url": meta["portal_url"],
                "source": "Council",
            })
        official_links += [
            {
                "title": f"{cname} contract awards on Contracts Finder",
                "url": "https://www.contractsfinder.service.gov.uk/Search/Results?&searchTerm="
                       + off_name.replace(" ", "+") + "&sort=relevance",
                "source": "Contracts Finder",
            },
            {
                "title": f"Ombudsman decisions about {cname} Council",
                "url": "https://www.lgo.org.uk/decisions",
                "source": "LGSCO",
            },
            {
                "title": f"Recorded crime & policing in {cname}",
                "url": "https://www.police.uk/",
                "source": "Police.uk",
            },
        ]

        raw_class = la_class_raw.get(code, "UA" if r["tier"] == "lower" and code not in parent_county_map else "SD")

        # ---- commercial / fiscal --------------------------------------------
        bor = borrowing.get(code)
        pop = population.get(code)
        debt_per_resident = round(bor["total_gbp_m"] * 1_000_000 / pop, 0) if (bor and bor.get("total_gbp_m") is not None and pop) else None

        out_councils[cname] = {
            "id": r["council_id"], "ons_code": code, "tier": r["tier"],
            "name": cname,
            "la_class": raw_class,
            "la_class_label": CLASS_LABELS.get(raw_class, "Local Authority"),
            "parent_county": parent_county_map.get(code),
            "parent_county_code": parent_county_code_map.get(code),
            "party": ctrl["bucket"] if ctrl else None,
            "party_full": ctrl["current"] if ctrl else None,
            "control": ctrl,
            "election": elec,
            "population": int(population[code]) if code in population else None,
            "ethnicity": ethnicity,
            "ethnicity_source": eth_source_by_ons.get(code, "Ethnicity, Census 2021 (ONS)"),
            "ethnicity_england": ethnicity_england,
            "topic_share": topic_share.get(code),
            "age_bands": age_by_name.get(cname),
            "money": money.get(code),
            "money_share": m_share,
            "talk_vs_spend": tvs,
            "scorecard": scorecard.get(code, []),
            "qol": qol_by_code.get(code),
            "financial_distress": distress_by_code.get(code),
            "reading_links": links,
            "official_links": official_links,
            "portal_url": (portal_by_ons.get(code) or {}).get("portal_url"),
            "borrowing": ({"total_gbp_m": bor["total_gbp_m"], "per_resident": debt_per_resident,
                           "rank": borrow_rank.get(code)}
                          if bor and bor.get("total_gbp_m") is not None else None),
            "contracts": contracts.get(code),
        }

    data = {
        "topics": TOPICS,
        "topic_colors": TOPIC_COLORS,
        "neutral_grey": NEUTRAL_GREY,
        "taxonomy_examples": TAXONOMY_EXAMPLES,
        "corpus_avg_topic_share": corpus_avg,
        "corpus_window": window,
        "money_average_per_resident": money_weighted_avg,
        "money_median_per_resident": money_weighted_avg,
        "finance_topics_england": ft_england,
        "qol_england": qol_england,
        "borrowing_england": borrow_eng,
        "distress_watchlist": distress_watchlist,
        "age_bands_mode": age_mode,
        "age_bands_order": AGE_BAND_ORDER,
        "age_bands_england": age_bands_england,
        "age_pyramid_england": age_pyramid_england,
        "party_groups_spend": party_groups_spend,
        "party_groups_discussion": party_groups_discussion,
        "party_by_tier": party_by_tier,
        "league_table": league_table,
        "councils": out_councils,
    }

    def clean(obj):
        if isinstance(obj, dict):
            return {k: clean(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [clean(v) for v in obj]
        if isinstance(obj, (np.integer, np.floating)):
            obj = obj.item()
        if isinstance(obj, float) and pd.isna(obj):
            return None
        try:
            if pd.isna(obj):
                return None
        except (TypeError, ValueError):
            pass
        return obj

    data = clean(data)
    out_path = SITE_DIR / "data.json"
    out_path.write_text(json.dumps(data, indent=None, default=str), encoding="utf-8")

    counts = {
        "councils": len(out_councils),
        "with_topic_share": sum(1 for c in out_councils.values() if c["topic_share"]),
        "with_population": sum(1 for c in out_councils.values() if c["population"] is not None),
        "with_ethnicity": sum(1 for c in out_councils.values() if c["ethnicity"]),
        "with_age_bands": sum(1 for c in out_councils.values() if c["age_bands"]),
        "with_money": sum(1 for c in out_councils.values() if c["money"]),
        "with_money_share": sum(1 for c in out_councils.values() if c["money_share"]),
        "with_talk_vs_spend": sum(1 for c in out_councils.values() if c["talk_vs_spend"]),
        "with_scorecard": sum(1 for c in out_councils.values() if c["scorecard"]),
        "with_qol": sum(1 for c in out_councils.values() if c.get("qol")),
        "with_financial_distress": sum(1 for c in out_councils.values() if c.get("financial_distress")),
        "with_momentum": sum(1 for c in out_councils.values() if c.get("momentum")),
        "with_control": sum(1 for c in out_councils.values() if c["control"]),
        "with_reading_links": sum(1 for c in out_councils.values() if c["reading_links"]),
        "with_ombudsman": sum(1 for c in out_councils.values() if c.get("ombudsman")),
        "with_borrowing": sum(1 for c in out_councils.values() if c.get("borrowing")),
        "with_contracts": sum(1 for c in out_councils.values() if c.get("contracts")),
        "party_groups_spend": len(party_groups_spend),
        "party_groups_discussion": len(party_groups_discussion),
        "league_rows": len(league_rows),
    }
    print(f"wrote {out_path} -- {counts}")


if __name__ == "__main__":
    main()
